---
# golangci-lint run \
#   --enable govet,revive,gosec,goconst,prealloc,stylecheck,unconvert,ineffassign,structcheck,gocritic \
#   --exclude-use-default=false --deadline=5m
run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - prealloc
    # - bodyclose
    # - deadcode
    # - depguard
    # - dogsled
    # - dupl
    # - errcheck
    # - exhaustive
    # - funlen
    # - gas
    # - gochecknoinits
    - goconst
    - gocritic
    # - gocyclo
    # - gofmt
    - goimports
    - revive
    # - gomnd
    # - goprintffuncname
    - gosec
    # - gosimple
    - govet
    - ineffassign
    # - lll
    # - megacheck
    # - misspell
    # - nakedret
    # - noctx
    # - nolintlint
    # - rowserrcheck
    # - scopelint
    # - staticcheck
    # - structcheck
    - stylecheck
    # - typecheck
    - unconvert
    # - unparam
    - unused
    # - varcheck
    # - whitespace
  fast: false
