project_name: clown

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: clown
    ldflags:
      - -s -w -X main.build={{.Version}}

brews:
  - tap:
      owner: rollwagen
      name: homebrew-tap
    license: Apache-2.0
    install: |-
      bin.install "clown"
      bash_completion.install "completions/clown.bash" => "clown"
      zsh_completion.install "completions/clown.zsh" => "_clown"
      fish_completion.install "completions/clown.fish"

checksum:
  name_template: 'checksums.txt'

archives:
  - files:
      - README.md
      - LICENSE
      - completions/*

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
